/* Inclusions */
#include "uthash.h"
#include "sock352.h"

/* Socket Hash Structure */
struct sock352_sockaddr_hash {
  int fd; /* file descriptor - to be used for the hash */
  sock352_sockaddr_t *socket; /* thing we are hashing bruh */
  UT_hash_handle hh; /* hashable mashable playable fun */
}; 

/* typedef it to something simple */
typedef struct sock352_sockaddr_hash sock352_sockaddr_hash_t; 

/* hashtable for sockets */
sock352_sockaddr_hash_t *sockets = NULL; 


/* ID generator */
int id = 0; //global

int nextId(){ //gives back teh next number - works cause we're not using persistant storage
  return id++; 
}

/* 
add a socket to the hash table 

return -1 if bad 
return socket_fd if OK
*/
int addSocket(sock352_sockaddr_t *socket){}

  //check to see if we have a non-NULL socket input
  if(!socket) return -1; 

  //generate the unique hash key 
  int socket_fd = 0; /* replace with some number generated by a hash */
  sock352_sockaddr_hash_t *newHash; //new hash object

  //check to see if we already used the socket_fd we generated (and continue to generate until we have a new one)
  do {
    socket_fd = nextId(); 
    HASH_FIND_INT(sockets, &socket_fd, socket_hash)
  } while(socket_hash);
  
  //create the new structure to be hashed
  sock352_sockaddr_hash_t *newHash = (sock352_sockaddr_hash_t *)calloc(1, sizeof(sock352_sockaddr_hash_t)); 
  newHash->fd = socket_fd; //set the key
  newHash->socket = socket; //set the socket

  HASH_ADD_INT(sockets, fd, socket); //hash the structure into the table
}

/* 
find a socket from the hash table

returns NULL if bad id 
returns the sock352_sockaddr_t if good
*/
sock352_sockaddr_t findSocket(int socket_fd){
  sock352_sockaddr_hash_t *socket_hash; //structure pointer

  //find the structure based on the fd
  HASH_FIND_INT(sockets, &socket_fd, socket_hash); 

  //check if we found it
  if(!socket_hash) return NULL; //didn't find it

  //found it  -- return the socket we stored inside
  if(socket_hash->socket) return socket_hash->socket; 
  else return NULL;
}


/* 
delete a socket from the hash table 

return 0 if failed 
return 1 if success
*/

int deleteSocket(int socket_fd){
  sock352_sockaddr_hash_t *socket_hash; //strcuture pointer

  //find the structure based on the file descriptor
  HASH_FIND_INT(sockets, &socket_fd, socket_hash); 

  //check if we found it
  if(!socket_hash) return 0; 

  //delete it
  HASH_DEL(sockets, socket_hash);
  free(socket_hash);
}